{"frames":[{"func":"modelsummary(models, coef_map = renamed_labels, statistic = \"std.error\", \n    stars = TRUE, add_rows = extra_rows, output = c(\"main_regressions.rtf\", \n        \"markdown\"), fmt = 3, gof_map = c(\"nobs\", \"r.squared\"))","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0},{"func":"sanitize_output(output)","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0},{"func":"insight::format_error(msg)","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0},{"func":"format_alert(..., type = \"error\")","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0},{"func":"stop(format_message(string = string, ..., line_length = line_length, \n    indent = indent), call. = call)","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0}],"message":"Error: The `output` argument must be a string. This error is sometimes raised when users\n  supply multiple models to `modelsummary` but forget to wrap them in a list. This\n  works: `modelsummary(list(model1, model2))`. This does *not* work:\n  `modelsummary(model1, model2)`\n"}